routes/web.php
<?php

use App\Models\Report;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\ReportController@index');
Route::resource('reports', 'App\Http\Controllers\ReportController');

URL::forceScheme('https');

app/Models/Report.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    protected $fillable = [
        'name',
        'icon'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Report;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ReportController extends Controller
{
    public function index()
    {
        $reports = Report::all();
        return view('pages.report', compact('reports'));
    }

    public function store(Request $request): RedirectResponse
    {
        DB::beginTransaction();

        try {
            $createFields = [
                'name' => $request->get('name'),
                'icon' => 'file'
            ];

            Report::create($createFields);

            DB::commit();

            return redirect()
                ->route('reports.index')
                ->with('error', 'Successfully inserted report.');

        } catch (\Exception $e) {
            DB::rollBack();

            return redirect()
                ->route('reports.index')
                ->with('error', 'Failed to insert report.');
        }
    }

    public function update(Request $request, $id): RedirectResponse
    {
        DB::beginTransaction();

        try {
            $updateFields = [
                'name' => $request->get('name')
            ];

            $report = Report::where('id', $id)->first();
            $report->update($updateFields);
            $report->save();

            DB::commit();

            return redirect()
                ->route('reports.index')
                ->with('error', 'Successfully updated report.');

        } catch (\Exception $e) {
            DB::rollBack();

            return redirect()
                ->route('reports.index')
                ->with('error', 'Failed to update report.');
        }
    }

    public function destroy($id): RedirectResponse
    {
        try {
            Report::where('id', $id)->delete();

            return redirect()
                ->route('reports.index')
                ->with('error', 'Successfully deleted report.');

        } catch (\Exception $e) {
            return redirect()
                ->route('reports.index')
                ->with('error', 'Failed to delete report.');
        }
    }
}

resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Storyclash | Report Management">

<link rel="icon" type="image/png" href="/img/favicon.png">
<link rel="stylesheet" type="text/css" href="{{ secure_asset('css/main.css') }}">

<title>Storyclash</title>

<script src="https://kit.fontawesome.com/1ef6e600b4.js" crossorigin="anonymous"></script>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    @include('includes.head')
</head>
<body>
<div class="container">
    <div id="main" class="row">
        @yield('content')
    </div>
</div>

<script type="text/javascript" src="{{ secure_asset('js/main.js') }}"></script>

</body>
</html>

resources/views/pages/report.blade.php
@extends('layouts.default')

@section('content')

    <div class="sidebar">
        <a class="active" id="sidebar-show" href="#">
            <img src="/img/favicon.png" alt="Storyclash" class="logo-img loading" data-was-processed="true">
        </a>
    </div>

    <div class="reports-subnav" id="sidebar-panel">
        <a class="btn btn-reports-subnav" id="sidebar-hide">
            <i class="fa-solid fa-angle-left"></i>
            <i class="fa-solid fa-bookmark"></i>
            Saved Reports
        </a>

        <button class="btn btn-reports-collection" id="accordion">
            My Reports
            <i class="fa fa-angle-down"></i>
        </button>

        <div class="reports-collection-content" id="panel">
            @foreach ($reports as $report)
                <div class="report-collection-item">
                    <div class="report-name">
                        <i class="fa-solid fa-{{ $report->icon }}"></i>

                        <form method="POST"
                              action="{{ route('reports.update', $report->id) }}"
                              class="report-name-form hide">
                            @csrf
                            @method('PUT')

                            <input type="submit" hidden>
                            <input type="text" id="name" name="name" class="report-name-form-input" value="{{ $report->name }}" required>
                        </form>

                        <span class="report-name-text">{{ $report->name }}</span>
                    </div>

                    <div class="report-menu">
                        <button class="btn btn-report-menu-button">
                            <i class="fa-solid fa-ellipsis-vertical"></i>
                        </button>
                        <div class="report-menu-content">
                            <button type="submit" class="btn btn-rename-report report-menu-item">
                                <i class="fa-solid fa-pen"></i>
                                Rename
                            </button>
                            <form method="POST"
                                  action="{{ route('reports.destroy', $report->id) }}"
                                  class="delete-report-form">
                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-delete-report report-menu-item">
                                    <i class="fa-solid fa-trash"></i>
                                    Delete
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach

            <div class="report-collection-item hide" id="new-report-collection-item">
                <div class="report-name">
                    <form method="POST"
                          action="{{ route('reports.store') }}"
                          class="new-report-collection-item-form">
                        @csrf
                        @method('POST')

                        <i class="fa-solid fa-file"></i>
                        <input type="submit" hidden>
                        <input type="text" id="icon" name="icon" value="file" hidden>
                        <input type="text" id="name" name="name" class="new-report-collection-item-form-input" required>
                    </form>
                </div>
            </div>

            <button type="submit" class="btn btn btn-save-report" id="btn-new-report">
                <i class="fa-solid fa-circle-plus"></i>
                Save Report
            </button>
        </div>
    </div>

    <div class="content">
    </div>

@stop